# Generated by Django 5.2.11 on 2026-02-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_broadcastlog_subscriber'),
        ('core', '0002_remove_subscriber_name'),
    ]

    operations = [
    ]
